// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import CatPng from "./images/cat.png";
import DogPng from "./images/dog.png";
import BirdPng from "./images/bird.png";
import FishPng from "./images/fish.png";
import UnknownPng from "./images/unknown.png";

var dog = DogPng;

var cat = CatPng;

var bird = BirdPng;

var fish = FishPng;

var unknown = UnknownPng;

function handleClick(_event) {
  console.log("clicked!");
  
}

function Animal(Props) {
  var species = Props.species;
  var name = Props.name;
  var src;
  switch (species) {
    case "bird" :
        src = bird;
        break;
    case "cat" :
        src = cat;
        break;
    case "dog" :
        src = dog;
        break;
    case "fish" :
        src = fish;
        break;
    default:
      src = unknown;
  }
  return React.createElement("div", {
              className: "horiz",
              onClick: handleClick
            }, React.createElement("img", {
                  alt: species,
                  src: src
                }), React.createElement("span", undefined, React.createElement("br", undefined)), name);
}

var make = Animal;

export {
  dog ,
  cat ,
  bird ,
  fish ,
  unknown ,
  handleClick ,
  make ,
  
}
/* dog Not a pure module */
