// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import CatPng from "./images/cat.png";
import DogPng from "./images/dog.png";
import BirdPng from "./images/bird.png";
import FishPng from "./images/fish.png";

var dog = DogPng;

var cat = CatPng;

var bird = BirdPng;

var fish = FishPng;

function handleClick(_event) {
  console.log("clicked!");
  
}

function Animal(Props) {
  var species = Props.species;
  var name = Props.name;
  return React.createElement("div", {
              onClick: handleClick
            }, "hello! My name is " + name + ", and I'm a " + species, React.createElement("img", {
                  alt: species,
                  src: dog
                }));
}

var make = Animal;

export {
  dog ,
  cat ,
  bird ,
  fish ,
  handleClick ,
  make ,
  
}
/* dog Not a pure module */
