// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import LogoSvg from "./logo.svg";
import * as Animal$AppTemplateReasonReact from "./Animal.bs.js";

var logo = LogoSvg;

import './App.css';
;

function App(Props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  React.useEffect((function () {
          var intervalId = setInterval((function (param) {
                  return Curry._1(setCount, (function (count) {
                                return count + 1;
                              }));
                }), 100);
          return (function (param) {
                    clearInterval(intervalId);
                    
                  });
        }), []);
  return React.createElement("div", {
              className: "App"
            }, React.createElement("header", {
                  className: "App-header"
                }, React.createElement("a", {
                      className: "App-link"
                    }, "go for it!"), React.createElement(Animal$AppTemplateReasonReact.make, {
                      species: "unknown",
                      name: "Donald"
                    }), React.createElement(Animal$AppTemplateReasonReact.make, {
                      species: "fish",
                      name: "Ella"
                    }), React.createElement(Animal$AppTemplateReasonReact.make, {
                      species: "dog",
                      name: "Lady"
                    }), React.createElement(Animal$AppTemplateReasonReact.make, {
                      species: "cat",
                      name: "Buffbuff"
                    }), React.createElement(Animal$AppTemplateReasonReact.make, {
                      species: "bird",
                      name: "Kim"
                    })));
}

var make = App;

export {
  logo ,
  make ,
  
}
/* logo Not a pure module */
