// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Caml_option = require("rescript/lib/js/caml_option.js");

function myMap(optValue, f) {
  if (optValue !== undefined) {
    return Caml_option.some(Curry._1(f, Caml_option.valFromOption(optValue)));
  }
  
}

function myFlatMap(optValue, f) {
  if (optValue !== undefined) {
    return Curry._1(f, Caml_option.valFromOption(optValue));
  }
  
}

function mySquare(x) {
  return x * x;
}

function mySqrt(x) {
  if (x >= 0.0) {
    return Math.sqrt(x);
  }
  
}

console.log(myMap(2.0, mySquare));

console.log(myMap(undefined, mySquare));

console.log(myFlatMap(2.0, mySqrt));

console.log(myFlatMap(undefined, mySqrt));

exports.myMap = myMap;
exports.myFlatMap = myFlatMap;
exports.mySquare = mySquare;
exports.mySqrt = mySqrt;
/*  Not a pure module */
