// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var discount = 0.10;

var total = 11 * 14.50;

var afterDiscount = total * (1.0 - discount);

console.log("Price before discount", total);

console.log("Price after discount", afterDiscount);

var qty = 11;

var price = 14.50;

exports.qty = qty;
exports.price = price;
exports.discount = discount;
exports.total = total;
exports.afterDiscount = afterDiscount;
/*  Not a pure module */
