// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function shirtSizeOfString(str) {
  switch (str) {
    case "L" :
        return /* Large */2;
    case "M" :
        return /* Medium */1;
    case "S" :
        return /* Small */0;
    case "XL" :
        return /* XLarge */{
                _0: 1
              };
    case "XXL" :
        return /* XLarge */{
                _0: 2
              };
    case "XXXL" :
        return /* XLarge */{
                _0: 3
              };
    case "XXXXL" :
        return /* XLarge */{
                _0: 4
              };
    default:
      return ;
  }
}

function price(size) {
  if (size === undefined) {
    return ;
  }
  if (typeof size !== "number") {
    return 16.00 + (size._0 - 1 | 0) * 0.50;
  }
  switch (size) {
    case /* Small */0 :
        return 11.00;
    case /* Medium */1 :
        return 12.50;
    case /* Large */2 :
        return 14.00;
    
  }
}

console.log(price(shirtSizeOfString("S")));

console.log(price(shirtSizeOfString("XXL")));

exports.shirtSizeOfString = shirtSizeOfString;
exports.price = price;
/*  Not a pure module */
