// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var discount = 0.05;

var total = 8 * 11.5;

var discountPrice = total * (1.0 - discount);

console.log("The total price is \xe2\x82\xac", total);

console.log("The discount price is \xe2\x82\xac", discountPrice.toString());

var qty = 8;

var price = 11.5;

exports.qty = qty;
exports.price = price;
exports.discount = discount;
exports.total = total;
exports.discountPrice = discountPrice;
/*  Not a pure module */
