// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var t_wc = 13.12 + 0.6215 * 5.0 + (0.3965 * 5.0 - 11.37) * Math.pow(20.0, 0.16);

console.log("At temperature " + ((5.0).toString() + (" degrees Celsius and wind speed " + ((20.0).toString() + (" km/h, the wind chill temperature is " + t_wc.toString())))));

var t = 5.0;

var v = 20.0;

exports.t = t;
exports.v = v;
exports.t_wc = t_wc;
/* t_wc Not a pure module */
