// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_option = require("rescript/lib/js/js_option.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");

function shirtSizeOfString(str) {
  switch (str) {
    case "L" :
        return /* Large */2;
    case "M" :
        return /* Medium */1;
    case "S" :
        return /* Small */0;
    case "XL" :
        return /* XLarge */{
                _0: 1
              };
    case "XXL" :
        return /* XLarge */{
                _0: 2
              };
    case "XXXL" :
        return /* XLarge */{
                _0: 3
              };
    case "XXXXL" :
        return /* XLarge */{
                _0: 4
              };
    default:
      return ;
  }
}

function price(size) {
  if (typeof size !== "number") {
    return 16.00 + (size._0 - 1 | 0) * 0.50;
  }
  switch (size) {
    case /* Small */0 :
        return 11.00;
    case /* Medium */1 :
        return 12.50;
    case /* Large */2 :
        return 14.00;
    
  }
}

function makeDisplayText(input, costStr) {
  return "Your " + input + " shirt costs EUR " + costStr;
}

function displayPrice(input) {
  var __x = Belt_Option.map(shirtSizeOfString(input), price);
  var __x$1 = Belt_Option.map(__x, (function (prim) {
          return prim.toString();
        }));
  var __x$2 = Belt_Option.map(__x$1, (function (param) {
          return makeDisplayText(input, param);
        }));
  var text = Js_option.getWithDefault("Cannot determine price for " + input, __x$2);
  console.log(text);
  
}

displayPrice("S");

displayPrice("XL");

displayPrice("XS");

exports.shirtSizeOfString = shirtSizeOfString;
exports.price = price;
exports.makeDisplayText = makeDisplayText;
exports.displayPrice = displayPrice;
/*  Not a pure module */
