// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var total = 7 * 14.5;

console.log("The total price is \xe2\x82\xac", total);

var qty = 7;

var price = 14.5;

exports.qty = qty;
exports.price = price;
exports.total = total;
/*  Not a pure module */
